lambda:
  timeout_seconds: 10
  env: dev
  backoff:
    max_retries: 3
    delay_seconds: 5
    backoff_factor: 0.5
    max_delay_seconds: 60

latinia:
  url: "https://api.dev.cuentafuturo.com/v1/mensajeria/latinia"
  mantenimiento: False
  auth: "https://bb-ms-core-dominio-cliente-dev.auth.us-east-1.amazoncognito.com/oauth2/token"
  timeout_seconds: 10
  secret_name_oauth: "mpg-ms-tokenizacion-batch/dev/secretCatalogoCognito"

db:
  secret_name_db: "mysql_mock"

s3:
  bucket_name: "bb-emisormdp-config"
sqs:
  queue_url: "https://sqs.us-east-1.amazonaws.com/308528169754/bb-notificaciones-reenvio"
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
    file:
      class: logging.FileHandler
      filename: "/dev-notificaciones-colas/logs/lambda.log"
      formatter: simple
  root:
    level: INFO
    handlers:
      - console
      - file