http:
  retries:
    total: 3
    backoff_factor: 0.5
    status_forcelist:
      - 500
      - 502
      - 503
      - 504
    allowed_methods:
      - "POST"
    respect_retry_after_header: true

ssm:
